force-app/main/default/objects/Account/fields/Backup_Sales_Representative__c.field-meta.xml
<CustomField>
    <fullName>Backup_Sales_Representative__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Backup  Sales Representative</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Backup  Sales Representative)</relationshipLabel>
    <relationshipName>BackupSalesRepresentative</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/DealerPrimaryPAAccountCode__c.field-meta.xml
<CustomField>
    <fullName>DealerPrimaryPAAccountCode__c</fullName>
    <description>The PA Account Code is the Parts and Accessories account that the dealerships use to book their service to.  Dealers can have multiple PA Account codes (one primary and multiple secondaries).  For most dealerships, this fields holds the primary PA Account</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Dealer Primary PA Account Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Participating_Programs__c.field-meta.xml
<CustomField>
    <fullName>Participating_Programs__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Participating Programs</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Sales_Representative__c.field-meta.xml
<CustomField>
    <fullName>Primary_Sales_Representative__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Sales Representative</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>PrimarySalesRepresentative</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Sales_Hours__c.field-meta.xml
<CustomField>
    <fullName>Sales_Hours__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Sales Hours</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Services_Offered__c.field-meta.xml
<CustomField>
    <fullName>Services_Offered__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Services Offered</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GetDealershipDetails.cls
public with sharing class GetDealershipDetails {
    
 
  // Used by LWC
  @AuraEnabled
  public static Account getDealershipByPACode(String paCode) {

    List<Account> dealerships = [
        SELECT Name,DealerPrimaryPAAccountCode__c,BillingStreet,BillingCity,BillingState,BillingPostalCode,
        Sales_Hours__c,Services_Offered__c,Participating_Programs__c,
        Primary_Sales_Representative__r.Name,Primary_Sales_Representative__r.Phone,Primary_Sales_Representative__r.Email,
        Backup_Sales_Representative__r.Name,Backup_Sales_Representative__r.Phone,Backup_Sales_Representative__r.Email
        FROM Account
        WHERE DealerPrimaryPAAccountCode__c= :paCode 
        WITH SECURITY_ENFORCED    
        LIMIT 1
    ];
    
    if (dealerships?.size() > 0) {
      Account result = dealerships[0];
      return result;
    }
    else{
      return null;
    }
  }
}