force-app/main/default/objects/Account/fields/DealerPrimaryPAAccountCode__c.field-meta.xml
<CustomField>
    <fullName>DealerPrimaryPAAccountCode__c</fullName>
    <description>The PA Account Code is the Parts and Accessories account that the dealerships use to book their service to.  Dealers can have multiple PA Account codes (one primary and multiple secondaries).  For most dealerships, this fields holds the primary PA Account</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Dealer Primary PA Account Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DealerPrimarySalesCode__c.field-meta.xml
<CustomField>
    <fullName>DealerPrimarySalesCode__c</fullName>
    <description>The dealer sales code identifies a specific dealership location within a country, division and region.    Dealerships can have more than one sales code (one primary and multiple secondaries).  For most dealerships, this field holds the primary sales code.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Dealer Primary Sales Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/InactiveMerged__c.field-meta.xml
<CustomField>
    <fullName>InactiveMerged__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Inactive / Merged</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Sync_To_MC__c.field-meta.xml
<CustomField>
    <fullName>Sync_To_MC__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Field indicating that the Account is eligible for synchronization to Marketing Cloud. The field should be unchecked for full sandbox org records that were copied from the production org in order to avoid SubscriberKey conflicts in Marketing Cloud.</description>
    <inlineHelpText>Field indicating that the Account is eligible for synchronization to Marketing Cloud. The field should be unchecked for full sandbox org records that were copied from the production org in order to avoid SubscriberKey conflicts in Marketing Cloud.</inlineHelpText>
    <label>Sync To MC</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Sync_To_MC__c.field-meta.xml
<CustomField>
    <fullName>Sync_To_MC__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field indicating that the Contact is eligible for synchronization to Marketing Cloud. The field should be unchecked for full sandbox org records that were copied from the production org in order to avoid SubscriberKey conflicts in Marketing Cloud.</description>
    <inlineHelpText>Field indicating that the Contact is eligible for synchronization to Marketing Cloud. The field should be unchecked for full sandbox org records that were copied from the production org in order to avoid SubscriberKey conflicts in Marketing Cloud.</inlineHelpText>
    <label>Sync To MC</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CustMergeReq__c/CustMergeReq__c.object-meta.xml
<CustomObject>
    <description>to be used load data related to merged requests. A schedule job will pick these records and perform Customer profile merge.</description>
    <label>Customer Merge Request</label>
    <nameField>
        <displayFormat>MR-{0}</displayFormat>
        <label>Merge Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Merge Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CustMergeReq__c/fields/Loser__c.field-meta.xml
<CustomField>
    <fullName>Loser__c</fullName>
    <description>externalid__c  of  Loser customer</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Loser</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustMergeReq__c/fields/Merged__c.field-meta.xml
<CustomField>
    <fullName>Merged__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field to update after merge process is completed</description>
    <label>Merged ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CustMergeReq__c/fields/Winner__c.field-meta.xml
<CustomField>
    <fullName>Winner__c</fullName>
    <description>externalid__c  of Winner customer</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Winner</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Sync_To_MC__c.field-meta.xml
<CustomField>
    <fullName>Sync_To_MC__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Field indicating that the User is eligible for synchronization to Marketing Cloud. The field should be unchecked for full sandbox org records that were copied from the production org in order to avoid SubscriberKey conflicts in Marketing Cloud.</description>
    <inlineHelpText>Field indicating that the User is eligible for synchronization to Marketing Cloud. The field should be unchecked for full sandbox org records that were copied from the production org in order to avoid SubscriberKey conflicts in Marketing Cloud.</inlineHelpText>
    <label>Sync To MC</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/TestFactory.cls
/* @group: Test factory
 * @description: Generic class to setup data in test class
 */
@isTest
public class TestFactory {

    /*@description: Create Accounts for test class.
     */
    public static List<Account> createAccounts( Integer numberOfAccounts, String recordTypeId) {
        List<Account> accountList = new List<Account>();
        for ( Integer i = 0 ; i < numberOfAccounts ; i++ ) {
            Account account = new Account( firstname = 'Test' + Math.random(), lastname = 'Account',RecordTypeID=recordTypeId,
                                         InactiveMerged__c = False, DealerPrimaryPAAccountCode__c = '1234ABC', 
                                         DealerPrimarySalesCode__c = 'EFDR33');
            accountList.add(account);
        }
        return accountList;
    }

    /*@description: Create Customer Merge Request records for Customer Profile Merge.
     */
    public static List<CustMergeReq__c> createMergeReq(Integer numberOfCustMerge, List<String> winner, List<String> loser) {
        List<CustMergeReq__c> cmrList = new List<CustMergeReq__c>();
        for ( Integer i = 0 ; i < numberOfCustMerge ; i++ ) {
            CustMergeReq__c mergeRequest = new CustMergeReq__c(loser__c = loser[i],winner__c = winner[i],Merged__c = False );
            cmrList.add( mergeRequest);
        }
        return cmrList;
    }

    /*
     *@description: Create Contact records.
     */
    public static List<Contact> createContacts(Integer numberOfContact){
        List<Contact> contactList = new List<Contact>();
        for ( Integer i = 0 ; i < numberOfContact ; i++ ) {
            Contact conObj = new Contact(LastName = 'Test',
                                         Email='test@example.com',
                                         Phone='1234567891',
                                         Sync_To_MC__c = false);
            contactList.add( conObj);
        }
        return contactList;

    }

    /*
     *@description: Create user records
     */
    public static User createUser(Id profileId, Id userRoleId, String firstname, String lastName){
        String orgId = UserInfo.getOrganizationId();
        Integer randomInt = Integer.valueOf(math.rint(math.random()*1000000));
        String uniqueName = orgId  + randomInt;
        User usrObj = new User(  firstname = firstname,
                                lastName = lastName,
                                email = uniqueName + '@test' + '.org',
                                Username = uniqueName + '@test' + '.org',
                                EmailEncodingKey = 'ISO-8859-1',
                                Alias = uniqueName.substring(18, 23),
                                TimeZoneSidKey = 'America/Los_Angeles',
                                LocaleSidKey = 'en_US',
                                LanguageLocaleKey = 'en_US',
                                ProfileId = profileId,
                                UserRoleId = userRoleId);
        return usrObj;
    }
}