force-app/main/default/objects/Account/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CustMergeCS__c/fields/Last_Batch_Run_Time__c.field-meta.xml
<CustomField>
    <fullName>Last_Batch_Run_Time__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Last Batch Run Time</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustMergeReq__c/CustMergeReq__c.object-meta.xml
<CustomObject>
    <description>to be used load data related to merged requests. A schedule job will pick these records and perform Customer profile merge.</description>
    <label>Customer Merge Request</label>
    <nameField>
        <displayFormat>MR-{0}</displayFormat>
        <label>Merge Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Merge Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CustMergeReq__c/fields/Failed__c.field-meta.xml
<CustomField>
    <fullName>Failed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this box if processing is Failed</description>
    <label>Failed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CustMergeReq__c/fields/Loser__c.field-meta.xml
<CustomField>
    <fullName>Loser__c</fullName>
    <description>externalid__c  of  Loser customer</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Loser</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustMergeReq__c/fields/Merged__c.field-meta.xml
<CustomField>
    <fullName>Merged__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field to update after merge process is completed</description>
    <label>Merged ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CustMergeReq__c/fields/ProcessedTime__c.field-meta.xml
<CustomField>
    <fullName>ProcessedTime__c</fullName>
    <description>Date/timestamp when customer merge process completed in Salesforce core.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Processed Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <label>Person Account</label>
</RecordType>

force-app/main/default/classes/CustomerMergeRequestBatch_Test.cls
/* @description: Test class for CustomerMergeRequestBatch
 */
@isTest
public class CustomerMergeRequestBatch_Test {
    
     /*
     * @description: This method prepares the test datas well as covers the positive and negative scenario.
     */
    @isTest
     public static void testCustomerMerge(){
        
        String formatedDt = System.now().addHours(-1).formatGMT('yyyy-MM-dd\'T\'HH:mm:ss\'Z\'');
        CustMergeCS__c cus = new CustMergeCS__c();
        cus.Name = 'Merge Batch Run Time';
        cus.Last_Batch_Run_Time__c = formatedDt;
        insert cus;
        
        String recordTypeId  = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PersonAccount').getRecordTypeId();
        List<String> extList = new list<String> { '11299885521' , '11256478219', '11299885777', '11256478999' };
   
        List<Account> insertAccList = TestFactory.createAccounts(4,recordTypeId);
        
        for( Integer i = 0 ; i < 4 ; i++ ){
            insertAccList[i].ExternalId__c = extList[i];
            
        }
        Insert insertAccList;
        
        List<CustMergeReq__c> cmrList = new List<CustMergeReq__c>();
        List<String> wList = new list<String> { '11299885521','132465', '11299885521', '11299885521'};
        List<String> lList = new list<String> { '11256478219','987654', '11299885777', '11256478999'};
        
        List<CustMergeReq__c> mergeList = TestFactory.createMergeReq(4,wList,lList); 
 		cmrList.addAll(mergeList); 
        Insert cmrList;
         
        Test.startTest();
        CustomerMergeRequest_Batch req = new CustomerMergeRequest_Batch();
		database.executeBatch(req);
        Test.stopTest();
        
        CustMergeReq__c cmrpositive = [SELECT Id, Processedtime__c, Merged__c 
                                   FROM CustMergeReq__c 
                                   WHERE loser__c = '11256478219'];
        
        system.debug('cmrpositive=>'+ cmrpositive);
        system.assertEquals(True,cmrpositive.Merged__c,'Merged');
        
        CustMergeReq__c cmrnegative = [SELECT Id, Processedtime__c, Merged__c,Failed__c 
                                   FROM CustMergeReq__c 
                                   WHERE loser__c = '987654'];
        
        system.debug('cmrnegative=>'+ cmrnegative);
        system.assertEquals(True,cmrnegative.Failed__c,'Falied CMR Scenario');
        
    }
    /*
	* @description: This method tests the scheduler method of the Batch Class.
	*/
     @isTest
    public static void scheduleBatch(){

        CustomerMergeRequest_Batch sched = new CustomerMergeRequest_Batch();
        String sch = '0 0 0 1 * ? *';
        String jobID = system.schedule('Merge Job', sch, sched);
        system.assertNotEquals(Null, jobID,'Schedule job');

    }
    
}