force-app/main/default/objects/CustMergeReq__c/CustMergeReq__c.object-meta.xml
<CustomObject>
    <description>to be used load data related to merged requests. A schedule job will pick these records and perform Customer profile merge.</description>
    <label>Customer Merge Request</label>
    <nameField>
        <displayFormat>MR-{0}</displayFormat>
        <label>Merge Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Merge Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CustMergeReq__c/fields/Loser__c.field-meta.xml
<CustomField>
    <fullName>Loser__c</fullName>
    <description>externalid__c  of  Loser customer</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Loser</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustMergeReq__c/fields/Merged__c.field-meta.xml
<CustomField>
    <fullName>Merged__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field to update after merge process is completed</description>
    <label>Merged ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CustMergeReq__c/fields/Merged_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Merged_Date_Time__c</fullName>
    <description>Timestamp when Merge happened in MDM</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Merged Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/CustMergeReq__c/fields/ProcessedTime__c.field-meta.xml
<CustomField>
    <fullName>ProcessedTime__c</fullName>
    <description>Date/timestamp when customer merge process completed in Salesforce core.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Processed Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/CustMergeReq__c/fields/Winner__c.field-meta.xml
<CustomField>
    <fullName>Winner__c</fullName>
    <description>externalid__c  of Winner customer</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Winner</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CustomerMergeRequest_Batch.cls
public class CustomerMergeRequest_Batch implements Database.Batchable<sObject>, Schedulable,Database.Stateful{
    public Datetime currentExecutionTime = System.now().addHours(-8);

 /****************************************************************************************************************
* @Description: Start method will fetch all the Customer Merge Request records created or updated in the system.
* @param :      Standard parameter where id = \'a0T8G0000006zUHUAY\' where Merged__c = False
* @Returns:
*****************************************************************************************************************/
    public Database.QueryLocator  start(Database.BatchableContext bc){
        String lastBatchExecutionTime = UtilityClass.fetchMergeBatchexecutionTime();
        String query = '';
        query = 'select ID,winner__c,loser__c,Merged__c,merged_date_time__c,Processedtime__c from CustMergeReq__c '+
            'where Merged__c = False AND LastModifiedDate >='+lastBatchExecutionTime ;
            System.debug('query=> ' + query);
        try{
            return Database.getQueryLocator(query);
        }catch(Exception e){
            return null;
        }
    }

/****************************************************************************************************************
* @Description: Execute method will get the Customer Merge Request records from the start method and iterate on them to perform
				merge operation on them.
* @param :      Customer Merge Request
* @Returns:
*****************************************************************************************************************/
    public void execute(System.SchedulableContext st){
        Database.executeBatch(new CustomerMergeRequest_Batch(),120);
    }

    public void execute (Database.BatchableContext bc, List<CustMergeReq__c> mergeReqs){
        Map<String,CustMergeReq__c> loserCMRMap = new Map<String,CustMergeReq__c>();
        Set<String> loserSet = new Set<String> ();
        Set<String> winSet = new Set<String> ();
        for(CustMergeReq__c cusMerge : mergeReqs){
            if(!String.isBlank(cusMerge.winner__c) ){
                winSet.add(cusMerge.winner__c);
            }
            if(!String.isBlank(cusMerge.loser__c) ){
                loserSet.add(cusMerge.loser__c);
            }
            loserCMRMap.put(cusMerge.loser__c,cusMerge);
        }
        AccountMergeService.handleAccountMerge(winSet, loserSet, loserCMRMap);
    }

/****************************************************************************************************************
* @Description:
* @param :      Database.BatchableContext bc
* @Returns:     NA
*****************************************************************************************************************/
    public void finish(Database.BatchableContext bc){
        UtilityClass.updateBatchTime(currentExecutionTime);
    }
}